
package com.alec.ws.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DataTypeWSImplService", targetNamespace = "http://cxf.ws.alec.com/", wsdlLocation = "http://localhost:8989/datatypeWS?wsdl")
public class DataTypeWSImplService
    extends Service
{

    private final static URL DATATYPEWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DATATYPEWSIMPLSERVICE_EXCEPTION;
    private final static QName DATATYPEWSIMPLSERVICE_QNAME = new QName("http://cxf.ws.alec.com/", "DataTypeWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8989/datatypeWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATATYPEWSIMPLSERVICE_WSDL_LOCATION = url;
        DATATYPEWSIMPLSERVICE_EXCEPTION = e;
    }

    public DataTypeWSImplService() {
        super(__getWsdlLocation(), DATATYPEWSIMPLSERVICE_QNAME);
    }

    public DataTypeWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DATATYPEWSIMPLSERVICE_QNAME, features);
    }

    public DataTypeWSImplService(URL wsdlLocation) {
        super(wsdlLocation, DATATYPEWSIMPLSERVICE_QNAME);
    }

    public DataTypeWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DATATYPEWSIMPLSERVICE_QNAME, features);
    }

    public DataTypeWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataTypeWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DataTypeWS
     */
    @WebEndpoint(name = "DataTypeWSImplPort")
    public DataTypeWS getDataTypeWSImplPort() {
        return super.getPort(new QName("http://cxf.ws.alec.com/", "DataTypeWSImplPort"), DataTypeWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataTypeWS
     */
    @WebEndpoint(name = "DataTypeWSImplPort")
    public DataTypeWS getDataTypeWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cxf.ws.alec.com/", "DataTypeWSImplPort"), DataTypeWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATATYPEWSIMPLSERVICE_EXCEPTION!= null) {
            throw DATATYPEWSIMPLSERVICE_EXCEPTION;
        }
        return DATATYPEWSIMPLSERVICE_WSDL_LOCATION;
    }

}
