
package com.alec.ws.cxf;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DataTypeWS", targetNamespace = "http://cxf.ws.alec.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataTypeWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.alec.ws.cxf.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudentsBySalary", targetNamespace = "http://cxf.ws.alec.com/", className = "com.alec.ws.cxf.GetStudentsBySalary")
    @ResponseWrapper(localName = "getStudentsBySalaryResponse", targetNamespace = "http://cxf.ws.alec.com/", className = "com.alec.ws.cxf.GetStudentsBySalaryResponse")
    public List<Student> getStudentsBySalary(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @return
     *     returns com.alec.ws.cxf.GetAllStudentsMapResponse.Return
     */
    @WebMethod
    @WebResult(name = "_return", targetNamespace = "")
    @RequestWrapper(localName = "getAllStudentsMap", targetNamespace = "http://cxf.ws.alec.com/", className = "com.alec.ws.cxf.GetAllStudentsMap")
    @ResponseWrapper(localName = "getAllStudentsMapResponse", targetNamespace = "http://cxf.ws.alec.com/", className = "com.alec.ws.cxf.GetAllStudentsMapResponse")
    public com.alec.ws.cxf.GetAllStudentsMapResponse.Return getAllStudentsMap();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.alec.ws.cxf.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudentById", targetNamespace = "http://cxf.ws.alec.com/", className = "com.alec.ws.cxf.GetStudentById")
    @ResponseWrapper(localName = "getStudentByIdResponse", targetNamespace = "http://cxf.ws.alec.com/", className = "com.alec.ws.cxf.GetStudentByIdResponse")
    public Student getStudentById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://cxf.ws.alec.com/", className = "com.alec.ws.cxf.AddStudent")
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://cxf.ws.alec.com/", className = "com.alec.ws.cxf.AddStudentResponse")
    public boolean addStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        Student arg0);

}
