
package com.alec.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMyService", targetNamespace = "http://ws.alec.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMyService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.alec.com/", className = "com.alec.ws.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.alec.com/", className = "com.alec.ws.AddResponse")
    @Action(input = "http://ws.alec.com/IMyService/addRequest", output = "http://ws.alec.com/IMyService/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "minus", targetNamespace = "http://ws.alec.com/", className = "com.alec.ws.Minus")
    @ResponseWrapper(localName = "minusResponse", targetNamespace = "http://ws.alec.com/", className = "com.alec.ws.MinusResponse")
    @Action(input = "http://ws.alec.com/IMyService/minusRequest", output = "http://ws.alec.com/IMyService/minusResponse")
    public int minus(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
